version: '3.9'

services:
  nestapp:
    container_name: nestapp
    image: robsoncarvalho/nestjs:1.0.0
    build: .
    ports:
      - 3000:3000
    environment:
      - JWT_SECRET_KEY=QWRFk1EK2t4ot/bZU+KTlI28c9OWjRVsdqWjTfTqamE=
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - SYNCHRONIZE=false
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
